### ISSUE TITLE
hf-api/range doesn't return a range

### ISSUE THREAD

**Issue by jColeChanged** [cnuernber/ham-fisted#13]
Is the intended behavior of hf-api/range when seqed to not be a range?  I can use hf-api/vec with hf-api/range to get reasonable results, but if I leave that out the behavior surprises me. 

Input:

(hf-api/range 10 20)

Expected behavior:
[10 11 12 13 14 15 16 17 18 19]

Actual behavior:
[10 10 10 10 10 10 10 10 10 10]

Input:

(hf-api/range 40)

Expected Behavior
(range 40)

Actual Behavior
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 32 32 32 32 32 32 32 32]

**Comment by cnuernber** [comment]
wow that is super wrong.  I think it reduces just fine but its chunking behavior is wrong.
