### ISSUE TITLE
`concatv` duplicating items

### ISSUE THREAD

**Issue by eneroth** [cnuernber/ham-fisted#2]
I'm seeing some really strange results with `concatv`. I end up with vectors containing all results, twice.

I'm comparing against a naive implementation of the same function:

```clojure 
(defn naive-concatv
  ([]
   [])
  ([x]
   (vec x))
  ([x & ys]
   (into (vec x) cat ys)))
```

And comparing them like this:

```clojure 
(defn concatv 
  [& args]
  (let [res1 (apply hf/concatv args)
        res2 (apply naive-concatv args)]
    (when-not (= res1 res2)
      (clojure.pprint/pprint {:args args
                              :res1 res1
                              :res2 res2}))
    res2))
```

Here's an example output when the problem kicks in:
```clojure 
{:args ([] [[:particle/id #uuid "41e0506a-2932-5882-9f2f-e97760010948"]] [])
 :res1 [[:particle/id #uuid "41e0506a-2932-5882-9f2f-e97760010948"]
        [:particle/id #uuid "41e0506a-2932-5882-9f2f-e97760010948"]]
 :res2 [[:particle/id #uuid "41e0506a-2932-5882-9f2f-e97760010948"]]}
```

I can't reproduce this in the REPL. It only occurs when `concatv` is run inside our tests (with Kaocha). Could this be due to some subtlety regarding mutability and threads, seeing as the tests are run in parallel?

**Comment by cnuernber** [comment]
Not sure - I will take a look

**Comment by cnuernber** [comment]
I am not familiar with kaocha but there isn't a threading issue there - a new mutable list is created each time.  I also can't replicate this at the repl.

**Comment by cnuernber** [comment]
```clojure

ham-fisted.api> (def data (pmap #(apply concatv %) (repeat 100 args)))
#'ham-fisted.api/data
ham-fisted.api> (first data)
[[1]]
ham-fisted.api> (every? #(= [[1]] %) data)
true
ham-fisted.api> (first args)
[]
ham-fisted.api> args
[[] [[1]] []]
```

**Comment by cnuernber** [comment]
Could you put a few more failing cases here?

**Comment by cnuernber** [comment]
@eneroth - Any help here is appreciated - 
1.  We could create the same tests in this project with Koacha.
2.  More failing cases.
3. ANY form of multithreaded generative test that shows the same failure.

The error may not be in the concatv operation itself but potentially in the iteration or sequence mechanism.

**Comment by cnuernber** [comment]
Closing this until there is a repro of some type.  It seems we should be able to use some similar testing scheme to reproduce.
