### ISSUE TITLE
Cannot `nippy` me `mapmap`s

### ISSUE THREAD

**Issue by harold** [cnuernber/ham-fisted#6]
```clojure
> (require '[ham-fisted.api :refer [mapmap]])
nil
> (mapmap #(vector % %) (range 3))
{0 0, 1 1, 2 2}
> (require 'tech.v3.io)
nil
> (tech.v3.io/put-nippy! "mapmap.nippy" (mapmap #(vector % %) (range 3)))
Execution error (ExceptionInfo) at taoensso.nippy/throw-unfreezable (nippy.clj:1005).
Unfreezable type: class ham_fisted.ImmutHashTable
```

Additional stacktrace-y info:

```
1. Unhandled clojure.lang.ExceptionInfo
   Unfreezable type: class ham_fisted.ImmutHashTable
   {:type ham_fisted.ImmutHashTable, :as-str "{0 0, 1 1, 2 2}"}
                 nippy.clj: 1005  taoensso.nippy/throw-unfreezable
                 nippy.clj: 1002  taoensso.nippy/throw-unfreezable
                 nippy.clj: 1255  taoensso.nippy/eval4704/fn
                 nippy.clj:  569  taoensso.nippy/eval4368/fn/G
                 nippy.clj:  578  taoensso.nippy/eval4415/fn
                 nippy.clj:  570  taoensso.nippy/eval4396/fn/G
                 nippy.clj: 1356  taoensso.nippy/freeze/fn/fn
                 nippy.clj: 1356  taoensso.nippy/freeze/fn
                 nippy.clj: 1279  taoensso.nippy/call-with-bindings
                 nippy.clj: 1275  taoensso.nippy/call-with-bindings
                 nippy.clj: 1337  taoensso.nippy/freeze
                 nippy.clj: 1327  taoensso.nippy/freeze
                 nippy.clj: 1331  taoensso.nippy/freeze
                 nippy.clj: 1327  taoensso.nippy/freeze
                   edn.clj:   51  tech.v3.io.edn/put-nippy!
                   edn.clj:   49  tech.v3.io.edn/put-nippy!
                    io.clj:  246  tech.v3.io/put-nippy!
                    io.clj:  242  tech.v3.io/put-nippy!
```

:smile: :bow:

**Comment by harold** [comment]
I don't think it's important to me that it comes back in as a ham-fisted type. If it's easier to just make nippy think it's a Clojure persistent map, I think I'd be cool w/ that.

**Comment by cnuernber** [comment]
It is to me however important that mapmap works the way ti does - probably just add (map #(into {} %) (mapmap ...)) to the end will do it.  I can also add a nippy namespace to ham-fisted which would add support for the various types in it although I am slightly surprised that nippy doesn't check for the standard clojure map (or java map) interfaces.

**Comment by harold** [comment]
`(into {} ...)` is an interesting idea - I'll play with that.

Agreed that nippy duck typing it as a `IPersistentMap` would be nice - I wonder if taoensso would be interested.

**Comment by harold** [comment]
Looks like nippy works off `APersistentMap`: https://github.com/ptaoussanis/nippy/blob/8bfe599ca333aac756356ef49dde281647b8afe1/src/taoensso/nippy.clj#L1154

**Comment by harold** [comment]
Which then boils down to `reduce-kv`: https://github.com/ptaoussanis/nippy/blob/8bfe599ca333aac756356ef49dde281647b8afe1/src/taoensso/nippy.clj#L786

For which one needs to implement `IKVReduce`

:thinking:

**Comment by cnuernber** [comment]
All the maps - *all of them, mutable, immutable or otherwise* - do implement IKVReduce - https://github.com/cnuernber/ham-fisted/blob/master/java/ham_fisted/MapBase.java.  The reason they don't derive from APersistentMap is it has inefficient defaults for some things.  You cannot derive from two concrete classes anyway in Java so that would mean MapBase would be APersistentMap which would then apply to all mutable maps as well as immutable and transient.

**Comment by cnuernber** [comment]
Another solution would be to have another map base that *did* derive from apersistentmap for the immutable and transient maps.

**Comment by cnuernber** [comment]
Or I guess I can just diff the interfaces of apersistentmap and mapbase and see what the real ramifications would be of having them go the same way.

**Comment by cnuernber** [comment]
How does nippy support persistent vectors?  Does it hang off of apersistentvector?

**Comment by harold** [comment]
Looks like it: https://github.com/ptaoussanis/nippy/blob/8bfe599ca333aac756356ef49dde281647b8afe1/src/taoensso/nippy.clj#L22-L26

And then it boils down to `reduce`: https://github.com/ptaoussanis/nippy/blob/master/src/taoensso/nippy.clj#L785-L810
 - Which goes down to `IReduceInit` or `IReduce` iiuc...

Which is actually p interesting to think about - I might have just written `doseq`, but I'm not immediately sure of the differences/ramifications.

**Comment by cnuernber** [comment]
Well, the immut maps can be apersistentmaps.  The immut vectors can be apersistentvectors and I can work all that in.  

Tests pass on the nippy-support branch with apersistentmap-based immut array and hash table maps.

**Comment by cnuernber** [comment]
Fixed in latest release (beta-88)
