### ISSUE TITLE
Do `partition` and `partition-by` make any sense here in ham-fisted?

### ISSUE THREAD

**Issue by harold** [cnuernber/ham-fisted#8]
I guess specifically w/ lazy-noncaching?

**Comment by cnuernber** [comment]
I took a very careful look at [partition-by](https://cnuernber.github.io/ham-fisted/ham-fisted.lazy-noncaching.html#var-partition-by) and it was a bit faster to do it in the lazy-noncaching way - especially in when replacing clojure.core/partition-by in `->>` flows.

That is in just-released 2.001.  

I imagine partition would be the same but I would hesitate on that one.  It seems to me that we nearly always want partition-all and nearly never partition.  `partition-all` makes a lot of sense *especially* if the source container is randomly-addressable - then they are constant-time in-place operations.

**Comment by harold** [comment]
That's great - I'd @ the person who emailed about this, but I'm not sure their github username. I did send them the link to this issue, so they'll likely see it.

**Comment by cnuernber** [comment]
Partition-all is in finished - closing.
